CREATE TABLE `vinci_handoffs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`handoff_id` varchar(64) NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`conversation_id` int,
	`bot_user_id` int,
	`source` varchar(32) NOT NULL,
	`telegram_user_id` varchar(64) NOT NULL,
	`telegram_username` varchar(255),
	`lead_name` varchar(255),
	`business_type` varchar(64) NOT NULL,
	`main_problem` varchar(64) NOT NULL,
	`current_setup` varchar(64) NOT NULL,
	`urgency` varchar(32) NOT NULL,
	`lead_score` varchar(16) NOT NULL,
	`contact_preference` varchar(64) NOT NULL,
	`phone` varchar(50),
	`email` varchar(320),
	`summary` text,
	`last_user_message` text,
	`vinci_notes` text,
	`handoff_status` varchar(32) NOT NULL DEFAULT 'pending',
	`assigned_to` varchar(64) NOT NULL DEFAULT 'Leo',
	`booking_link_sent` int NOT NULL DEFAULT 0,
	`contact_captured` int NOT NULL DEFAULT 0,
	CONSTRAINT `vinci_handoffs_id` PRIMARY KEY(`id`),
	CONSTRAINT `vinci_handoffs_handoff_id_unique` UNIQUE(`handoff_id`)
);
